name: Build

on:
  push:
    branches: [main, develop]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v3
      with:
        node-version: '17'
    - name: Install Build Dependencies
      run: npm ci
    - name: Run Unit Tests
      run: npm run test
    - name: Upload Coverage to CodeCov
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_SECRET }}
        files: coverage/coverage-final.json
        verbose: true
    - name: Fetch ATT&CK STIX Data
      run: npm run fetch-attack
    - name: Fetch ATT&CK STIX Data
      run: npm run fetch-attack
    - name: Build Svelte Application
      run: npm run build
    # - name: Build Chrome Extension
    #   run: npm run package-chrome
    - uses: actions/upload-artifact@v3
      with:
        name: attack-powered-suit-chrome.zip
        path: |
          manifest.json
          public/**
